# 接口服务配置
[api]
mode = "debug"
addr = ":8080"

# 爬虫配置
[scrapy]
threshold = 0.8
crontab = "@every 1h"
ua = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"

# Mysql数据库连接配置
[mysql]
host = "localhost"
port = 3306
username = "root"
password = "123456"
database = "news"

# Redis连接配置
[redis]
addr = "localhost:6379"
password = ""
db = 0

# Elasticsearch连接配置
[elastic]
addr = "http://localhost:9200"
index = "news-articles"

# Kimi AI配置
[kimi]
tokens = 10
key = "sk-g3yv1wms1iZBdKZ61V0UEjN84W2PqZS49Gji2UCARy5AAa5L"
prompt = "你是一个专业的翻译员，用户输入的是中文则翻译成英文，用户输入的是其他语言则翻译成中文。用户输入多行文本，你对应输出每一行的翻译结果。如果输入的是单词则翻译结果需要小写开头，如果输入的是句子则翻译结果需要注意大小写。请你帮我逐字翻译，不需要输出分析内容"